### ISSUE TITLE
TagGroup Followup Items

### ISSUE THREAD

**Issue by tiffany-sy-lin** [adobe/react-spectrum#2837]
## To-Do

List is non-exhaustive and is open to discussion. Working off of comments made in this PR: https://github.com/adobe/react-spectrum/pull/1922

### High
- [x] TagGroup should not have 'grid' role if no tags which is causing an accessibility error. Either don't assign role or don't render TagGroup. Keep as grid role
- [x] Add aria-disabled to Tag props https://github.com/adobe/react-spectrum/pull/1922#discussion_r799686116
- [x] Ensure all Tags are generated the same way. `<Tag>apples</Tag>` vs `<Tag><Text>apples</Text></Tag>` https://github.com/adobe/react-spectrum/pull/1922#discussion_r798124454
- [] Ensure labelId is used correctly with aria-label and aria-labelledby for voiceover

### Medium
- [ ] <s>Double check why OSX voiceover and ctl-opt-arrow to the ClearButton it only says "dimmed" and not "dimmed and disabled button"</s> Non-issue. Cannot focus on the button
- [x] Export Item from react-stately in tag/src/index.ts

### Low
- [x] Remove 'grid' role prop from Tag.tsx (role already comes from tagProps)
- [x] TagGroup.test.tsx 'inputs' var name is confusing for tags. Change to 'tags'
- [x] TagGroup.test.tsx Should TagGroup allow aria-label on Item? https://github.com/adobe/react-spectrum/pull/1922#discussion_r799025404
- [x] TagGroup test for up/down arrows, rtl + horizontal
- [x] Change single use it.each tests to individual tests
- [x] Don't expose SpectrumTagProps
- [x] Remove if (isRemovable) logic from TagGroup.tsx
- [x] Remove onFocus in useTag. Not needed

## Discussion & Exploration
- [x] Should we focus on row or cell in the TagGroup? https://github.com/adobe/react-spectrum/pull/1922#discussion_r793922782. Either as long as everything works well 
- [x] Should disabled tags be focusable? https://github.com/adobe/react-spectrum/pull/1922#pullrequestreview-865306220. Leave as non-focusable
- [x] tag.focused() vs document.activeElement() in test. Which to use and why
- [ ] GridProps: potentially don't need to destructure tabIndex out https://github.com/adobe/react-spectrum/pull/1922#discussion_r793950297
