### ISSUE TITLE
Column Resizing Epic

### ISSUE THREAD

**Issue by snowystinger** [adobe/react-spectrum#3007]
GA blockers:
- [x] Spectrum custom cursors need to be re-added - https://github.com/adobe/react-spectrum/pull/3649
- [x] Aria docs example - https://github.com/adobe/react-spectrum/pull/3982

Bugs to fix:
- [x] Select all checkbox disappears in FF/Chrome
  - Go to story, "allowsresizing-many-columns-and-rows". Resize a column. Horizontally scroll. The select all checkbox in the header disappears.
  - Appears to be an issue with persisted keys because the select all checkbox is actually being removed from the dom
  - Resizing a column using keyboard (try 3rd col in "allows resizing, uncontrolled, sortable columns"). Make the column larger until you see the "select all" checkbox disappear. 
  - Also just scroll horizontally with mouse in many rows/cols story with resize
- [ ] Restore FF hover styles when menu closes https://github.com/orgs/adobe/projects/19/views/18?filterQuery=&pane=issue&itemId=18311574
  - Click a header menu open, click again to close. None of the resizers are visible until the mouse is moved.
- [x] Table body becomes out of sync with header on scoll. (Safari)
  - Goto "allowsResizing, uncontrolled, sortable columns", resize the "Title" column wider, so the "Author" column's right/end edge is outside of the table. Start to resize author. The table header scrolls the entire column and resizer into view, but the table body does not scroll. Headers and body aren't lined up.
- [ ] Once the Nubbin is visible, moving column to column should still display it. (Touch)
  - Resizing should end if you tap on the table body. Tapping on another column's header while in resize shouldn't cause the menu to open nor exit resizing.
- [ ] Resizer can separate in RTL languages, Safari https://github.com/orgs/adobe/projects/19/views/18?filterQuery=&pane=issue&itemId=18311610
- [ ] Holding enter key can cause rapid focus changes
  - If you press and hold the Enter key on the "Resize column" menu item, it goes into resizing mode, then immediately goes out of it, then opens the menu again. Check what usePress does to ignore repeat events, or do it on keyup.
- [x] Divider sticks out a little over the Nubbin for column resizing, FF https://github.com/orgs/adobe/projects/19/views/18?filterQuery=&pane=issue&itemId=11755040

--------------------------------------------------------- 
Beta Work
Summary of remaining items for Col resizing Beta:
- [x] useTableColumnResizeState takes table state, but needs the type on the hook - rob
- [x] RSP docs example, add beta label - daniel - https://github.com/adobe/react-spectrum/pull/3840
- [x] Layout performance PR needs reviews and merging - devon

More remaining
- [x] WHCM PR needs reviews and merging - https://github.com/adobe/react-spectrum/pull/3818
- [ ] Possibly should announce when resizing is done

Testing session:
- [x] Fix docs props for regex matches of ColumnSize - https://github.com/adobe/react-spectrum/pull/3856
- [x] Try to combine onResize and onMove before Aria release https://github.com/adobe/react-spectrum/pull/3672#discussion_r1046639321 - https://github.com/adobe/react-spectrum/pull/3858
- [x] Column header menu can appear off the side of the table https://github.com/adobe/react-spectrum/pull/3672#discussion_r1046639166
- [x] Find a way to pass onResize/onResizeEnd to TableLayout so we don't call it from the aria hook https://github.com/adobe/react-spectrum/pull/3672#discussion_r1041623875
- [x] https://github.com/adobe/react-spectrum/pull/3672#discussion_r1046593136
- [x] Determine why the row group doesn't get a hover change false https://github.com/adobe/react-spectrum/pull/3672#discussion_r1046589368

# 🙋 Feature Request

Refactor
- [ ] NOT DOING ~Move resizing code out of react-aria/react-stately to the react-spectrum package https://github.com/adobe/react-spectrum/issues/3024~ -abandoned, we do want to export these hooks
- [x] NOT DOING Figure out the smallest way to feature flag the resizing portion of the TableView component https://github.com/adobe/react-spectrum/issues/3025
   - Approach 1: pare down the existing resizing code so it is more granular (aka layout level instead of two whole components) see starting branch work https://github.com/adobe/react-spectrum/compare/refactor-table-column-resizing?expand=1
     - [ ] TableView and DeprecatedTableView rely on two fairly different implementations of the public TableLayout module, these need to be combined and non-breaking. Possibly by moving some of useTableColumnResizeState into TableLayout
     - [ ] Resizing a column shouldn't cause the whole table size to change, only internally to the table
   - Approach 2: ~Get rid of the deprecated TableView component and test to make sure there aren't breaks to existing logic we don't quite want to jump to full release immediately~
 - [x] Get new TableView behavior passing all tests https://github.com/adobe/react-spectrum/compare/tableview-col-resizing-works-with-tests?expand=1 
   - deletes spooky column
   - makes tests more accurate using modern jest timer mocks
   - removes deprecated table view from code path, now it can just be deleted
   
Features
- [x] RTL support https://github.com/adobe/react-spectrum/issues/3026
- [x] Controlled state (skip this for first alpha) https://github.com/adobe/react-spectrum/pull/3672
- [ ] NVDA/VO https://github.com/adobe/react-spectrum/issues/3028
  - [x] support for column width values https://github.com/adobe/react-spectrum/pull/3295
  - [x] support for announcing that a column is resizable, resizer should also announce the name of it's column when focused https://github.com/adobe/react-spectrum/pull/3295
  - [ ] should announce resizing has started/stopped
  - [x] support swiping to resize (should come through as arrow keys, role=slider might fix this) https://github.com/adobe/react-spectrum/pull/3295
- [x] Remove hardcoded strings and add translations - AN-286401 https://github.com/adobe/react-spectrum/pull/3258 and https://github.com/adobe/react-spectrum/pull/3210

Bug fixes/investigations
- [x] Remove setTimeout that is compensating for restoreFocus so that selecting resize from the menu actually moves focus to the resizer https://github.com/adobe/react-spectrum/issues/3027
- [x] Look into why "Allows resizing hiding columns" menu won't open on iPhone/Android. Make this work on iPad https://github.com/adobe/react-spectrum/pull/3258
- [x] Increase hit area for resizers, investigate https://github.com/adobe/react-spectrum/pull/3414
  - move resizers out of the column headers
  - relax our contains "paint" rule
  - zIndex?
  - make clicking on white space part of the resizer hit area instead of the menu button
  - findings of investigation is that relaxing our overflow/paint contains results in headers rendering that we shouldn't be able to see, see https://github.com/adobe/react-spectrum/pull/3258#discussion_r908825332
- [x] Move focus to a resizer, tab out and tab back into the table, focus should be sent to the resizer. Improve consistency of tabbing into and out of a resizable TableView in general. https://github.com/adobe/react-spectrum/pull/3258
- [x] @dannify to check windows touch screen resizing https://github.com/adobe/react-spectrum/pull/3258
- [x] Firefox active state isn't blue, it should be blue like the other browsers https://github.com/adobe/react-spectrum/pull/3414
- [x] VO in Safari announces too many columns, probably including the "Spooky column" https://github.com/adobe/react-spectrum/pull/3258
- [x] Resize cursor should change between EW to E or W cursor when hitting the bounds
  - [x] we need assets for custom cursors
- [x] Selectable rows should not gain hover state while resizing is happening
- [x] Resizer doesn't line up with divider between cells https://github.com/adobe/react-spectrum/pull/3258
- [x] Resizer stays blue after resizing with mouse if you hover again https://github.com/adobe/react-spectrum/pull/3414
- [x] TalkBack/VO swiping up/down doesn't resize the column (role=slider might fix this) https://github.com/adobe/react-spectrum/pull/3295
- [x] Android NVDA Firefox must switch into forms mode first (role=slider might fix this) https://github.com/adobe/react-spectrum/pull/3295
- [x] Tapping on a column header and selecting resize column briefly focuses resizer before focus is lost, hopefully this isn't the "clicking behind the menu item" issue https://github.com/adobe/react-spectrum/pull/3295
- [x] If the user resizes a column via mouse first and then tabs to the column header, keyboard navigation between column headers no longer works https://github.com/adobe/react-spectrum/pull/3414
- [x] In the "allowsResizing, uncontrolled, sortable columns story", click on the "Title" header to open the dropdown. It shows sort and resize column options. Select a sort option. The dropdown will not open again. https://github.com/adobe/react-spectrum/pull/3414
- [x] TableView resize last column, then resize a middle column, the entire table jumps as multiple columns resize at once https://github.com/adobe/react-spectrum/pull/3672

Design: see contribution site
- [x] if resizer is at end of table, there is a gap between it and the border of the table due to the rounded corner https://reactspectrum.blob.core.windows.net/reactspectrum/37b608f55dc16ca1fb00c2232c8252f4f2fb1a83/storybook/index.html?path=/story/tableview--allowsresizing-uncontrolled-dynamic-widths https://github.com/adobe/react-spectrum/pull/3414
- [x] Add chevron to indicate there is a menu in the header. Perhaps only on hover? https://github.com/adobe/react-spectrum/pull/3535
- [ ] ~Get a different focus indicator for resizers from design~
- [x] Full column divider line highlighting when resizing. https://github.com/adobe/react-spectrum/pull/3414
  - extremely difficult
- [x] Does resizer have enough contrast? Should only appear on hover
- [x] When hovering over the column headers, only the resizer for that column shows up, but I think it might make sense to show all column resizers? https://github.com/adobe/react-spectrum/pull/3295
- [x] After dragging a resizer with a mouse, it remains blue even when removing hover and coming back. I guess because it's focused. Should we even focus it with a mouse? If so, then where should we send focus afterward? Maybe the blue should only be the keyboard focus style unless it is actively being dragged? https://github.com/adobe/react-spectrum/pull/3295
- [x] A bigger Touch target https://github.com/adobe/react-spectrum/pull/3414

Nice to have:
- [x] get rid of all reference to resizing in useTableColumnHeader https://github.com/adobe/react-spectrum/pull/3295
- [x] ~change signature of useTableColumnResizeState so it's not GridNodes~ takes table state, but needs the type on the aria hook

## 🧢 Your Company/Team

RSP
.

**Comment by tiffany-sy-lin** [comment]
When setting a column `minWidth` to a percentage value and the rest of the columns to a `maxWidth` value and an extra wide table, the column with the `minWidth` values does not expand to fit the extra space like it does when `minWidth` is set to a numeric value
<img width="1021" alt="Screenshot 2022-12-20 at 13 44 44" src="https://user-images.githubusercontent.com/20674023/208783215-0142e886-3620-465f-b47e-6731e06a8abd.png">
```
const columns = [
  { key: 'id', label: 'ID', maxWidth: 50 },
  { key: 'name', label: 'Name', allowsToggle: false, minWidth: 100 },
  { key: 'info', hideHeader: true, allowsToggle: false },
  { key: 'hp', label: 'HP', align: 'right', maxWidth: 50 },
  { key: 'attack', label: 'Attack', align: 'right', maxWidth: 50 },
  { key: 'defense', label: 'Defense', align: 'right', maxWidth: 50 },
  { key: 'speed', label: 'Speed', align: 'right', maxWidth: 50 },
  { key: 'total', label: 'Total', align: 'right', maxWidth: 50 },
  { key: 'weight', label: 'Weight', align: 'right', maxWidth: 50 },
  { key: 'height', label: 'Height', align: 'right', maxWidth: 50 },
  { key: 'abilities', label: 'Abilities', minWidth: 100 },
];
// vs
const columns = [
  { key: 'id', label: 'ID', maxWidth: '5%' },
  { key: 'name', label: 'Name', allowsToggle: false, minWidth: '20%' },
  { key: 'info', hideHeader: true, allowsToggle: false },
  { key: 'hp', label: 'HP', align: 'right', maxWidth: '5%' },
  { key: 'attack', label: 'Attack', align: 'right', maxWidth: '5%' },
  { key: 'defense', label: 'Defense', align: 'right', maxWidth: '5%' },
  { key: 'speed', label: 'Speed', align: 'right', maxWidth: '5%' },
  { key: 'total', label: 'Total', align: 'right', maxWidth: '5%' },
  { key: 'weight', label: 'Weight', align: 'right', maxWidth: '5%' },
  { key: 'height', label: 'Height', align: 'right', maxWidth: '5%' },
  { key: 'abilities', label: 'Abilities', minWidth: '20%' },
];

<TableView aria-label="Table title">
  <TableHeader columns={columns}>
    {(column) => {
      console.log(column);
      const { key, label, ...otherProps } = column;
      return (
        <Column {...otherProps} key={key} align={key === 'level' ? 'end' : 'start'}>
          {label}
        </Column>
      );
    }}
  </TableHeader>
  <TableBody items={items}>
    {(item) => <Row>{(columnKey) => <Cell>{item[columnKey]}</Cell>}</Row>}
  </TableBody>
</TableView>

const items = [
  {
    "id": 1,
    "name": "Bulbasaur",
    "type1": "Grass",
    "type2": "Poison",
    "ability1": "Overgrow",
    "ability2": "",
    "abilityH": "Chlorophyll",
    "hp": 45,
    "attack": 49,
    "defense": 49,
    "spattack": 65,
    "spdefense": 65,
    "speed": 45,
    "total": 318,
    "weight": "15.2 lbs.",
    "height": "2'04\"",
    "percentM": "0.875",
    "percentF": "0.125"
  },
  {
    "id": 2,
    "name": "Ivysaur",
    "type1": "Grass",
    "type2": "Poison",
    "ability1": "Overgrow",
    "ability2": "",
    "abilityH": "Chlorophyll",
    "hp": 60,
    "attack": 62,
    "defense": 63,
    "spattack": 80,
    "spdefense": 80,
    "speed": 60,
    "total": 405,
    "weight": "28.7 lbs.",
    "height": "3'03\"",
    "percentM": "0.875",
    "percentF": "0.125"
  },
  {
    "id": 3,
    "name": "Venusaur",
    "type1": "Grass",
    "type2": "Poison",
    "ability1": "Overgrow",
    "ability2": "",
    "abilityH": "Chlorophyll",
    "hp": 80,
    "attack": 82,
    "defense": 83,
    "spattack": 100,
    "spdefense": 100,
    "speed": 80,
    "total": 525,
    "weight": "220.5 lbs.",
    "height": "6'07\"",
    "percentM": "0.875",
    "percentF": "0.125"
  }];
```

**Comment by snowystinger** [comment]
@tiffany-sy-lin I've addressed your issue in https://github.com/adobe/react-spectrum/pull/3879

**Comment by snowystinger** [comment]
Closing, remaining items are captured in backlog
